name: 'tvl-push'

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  validate-and-build:
    uses: ./.github/workflows/generate_build_tvl.yml
  update-readme:
    runs-on: ubuntu-latest
    needs: validate-and-build
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.checkout_ref }}
    - name: 'Install packages'
      run: |
        sudo apt-get update
        sudo apt-get install graphviz-dev util-linux
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: 'Install python dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup Git Creds
      run: |
        git reset --hard
        git config --global user.email "johannes.pietrzyk@tu-dresden.de"
        git config --global user.name "GitHub Action (Maintainer: Johannes Pietrzyk)"
        python3 main.py --generate-readme-files --generate-readme-files
        git commit -a -m "Updated Readmes"
        git push