name: 'docker-test'

env:
  DOCKERHUB_NAMESPACE: jpietrzyktud
  DOCKERHUB_REPOSITORY: tvlgen
  DOCKERHUB_REGISTRY: docker.io
  DOCKER_IMAGE_TAG: ${{ github.ref_name }} 
  CONTAINER_TVLGEN_ROOT: /tvlgen

on: push

jobs:
  # create-env:
  #   name: Create and push Docker container
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2.1.0
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USER }}
  #         password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  #     - name: Extract metadata for Docker
  #       id: meta
  #       uses: docker/metadata-action@v4.3.0
  #       with:
  #         images: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.DOCKERHUB_REPOSITORY }}
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
  stuff:
    runs-on: ubuntu-latest
    steps:
      - name: "BLA"
        run: echo "$DOCKERHUB_REGISTRY/$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:$DOCKER_IMAGE_TAG"
