name: 'docker-test'

on: push

env:
  DOCKERHUB_REPOSITORY: tvlgen
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_IMAGE: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPOSITORY }}
  DOCKER_IMAGE_TAGGED:  ${{ env.DOCKER_IMAGE }}:${{ github.ref }}
  DOCKERHUB_IMAGE_FQN: ${{ env.DOCKERHUB_REGISTRY }}/${{ DOCKER_IMAGE_TAGGED }}
  CONTAINER_TVLGEN_ROOT: /tvlgen

jobs:
  create-env:
    name: Create and push Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      # - name: Build Docker Image
      #   run: |
      #     ID=$(docker build -q -t tvlgen_docker .)
      #     docker tag $ID tvlgen_docker:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.DOCKER_IMAGE }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_TAGGED }}
          #labels
      #- name: Push Docker Image
      #  run: docker push ghcr.io/jpietrzyktud/tvlgen_docker:latest
  generate:
    name: Generate TVL
    needs: create-env
    runs-on: ubuntu-latest
    container:
      image: ${DOCKERHUB_IMAGE_FQN}
      volumes:
        - ${{ github.workspace }}:${{ env.CONTAINER_TVLGEN_ROOT }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Running Generation
        run: cmake -S ${{ env.CONTAINER_TVLGEN_ROOT }} -B ${{ env.CONTAINER_TVLGEN_ROOT }/tvl