name: 'docker-test'

on: push
env:
  DOCKERHUB_REPOSITORY: tvlgen
  DOCKERHUB_REGISTRY: docker.io
  DOCKER_IMAGE_TAG: ${{ github.ref }} 
  CONTAINER_TVLGEN_ROOT: /tvlgen

jobs:
  create-env:
    name: Create and push Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ secrets.DOCKER_HUB_USER }}/${{ env.DOCKERHUB_REPOSITORY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
  generate:
    name: Generate TVL
    needs: create-env
    runs-on: ubuntu-latest
    container:
      image: "${{ env.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKER_HUB_USER }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}"
      volumes:
        - ${{ github.workspace }}:${{ env.CONTAINER_TVLGEN_ROOT }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Running Generation
        run: cmake -S ${{ env.CONTAINER_TVLGEN_ROOT }} -B ${{ env.CONTAINER_TVLGEN_ROOT }/tvl