name: 'docker-test'

on: push

jobs:
  create-env:
    name: Create and push Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          ID=$(docker build -q -t tvlgen_docker .)
          docker tag $ID tvlgen_docker:latest
      - name: Push Docker Image
        run: docker push ghcr.io/JPietrzykTUD/tvlgen:latest
  generate:
    name: Generate TVL
    runs-on: ubuntu-latest
    container:
      image: tvlgen:latest
      volumes:
        - ${{ github.workspace }}:/tvlgen
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Running composer install
        run: composer install
      - name: Running Generation
        run: cmake -B tvl