name: 'tvl-generate-build'

on:
  workflow_call:
    inputs:
      checkout_ref:
        description: >
          Branch / tag / SHA which is forwarded to actions/checkout@v3::ref
        default: ''
        required: false
        type: string

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/test_tvlgen.yml
    with:
      checkout_ref: ${{ inputs.checkout_ref }}
  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - uses: actions/TvlMergeTest@v1
      with:
        checkout_ref: ${{ inputs.checkout_ref }}
    # - name: 'Loads State'
    #   uses: actions/cache/restore@v3
    #   with:
    #     path: ./
    #     key: ${{ runner.os }}}-${{ env.GITHUB_SHA }}-checked-out
    - name: 'Generate TVL'
      run: |
        cmake -B tvl
    - name: 'Build TVL'
      run: |
        make -C tvl
    - name: 'Run Tests'
      run: |
        ./tvl/tvl/generator_output/src/test/tvl_test