name: 'tvl-generate-build'

inputs:
  checkout_ref:
    description: >
      Branch / tag / SHA which is forwarded to actions/checkout@v3::ref
    default: ''
    required: false

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/test_tvlgen.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - name: 'Generate TVL'
      run: |
        cmake -B tvl
    - name: 'Build TVL'
      run: |
        make -C tvl
    - name: 'Run Tests'
      run: |
        ./tvl/tvl/generator_output/src/test/tvl_test