name: 'tvlgen-validate-pr'

on:
  pull_request:
    branches: ['main']
    types: ['opened', 'reopened']


jobs:
  validate-generator:
    uses: ./.github/workflows/validate_generator.yml
    secrets: inherit
    with:
      checkout_ref: ${{ github.event.pull_request.head.sha }}