name: 'validate-tvlgen'

on:
  workflow_call:
    inputs:
      checkout_ref:
        description: >
          Branch / tag / SHA which is forwarded to actions/checkout@v3::ref
        default: ''
        required: false
        type: string

permissions:
  contents: read

jobs:
  init-env:
    uses: ./.github/workflows/init_env.yml
    with:
      checkout_ref: ${{ inputs.checkout_ref }}
  validate:
    name: Checking Generator Sources
    needs: init-env
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.init-env.outputs.image }}
      volumes:
        - ${{ github.workspace }}:/tvlgen
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          checkout_ref: ${{ inputs.checkout_ref }}
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 /tvlgen --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 /tvlgen --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Running Generation
        run: python3 /tvlgen/main.py